package projectx

import (
	"errors"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/weshofmann/boxwarden/internal/domain"
)

// List reads validated bookmarks without creating directories, locks, or
// receipts. An absent projects child is empty only after the state root itself
// has been admitted; an unavailable root must never become an empty registry.
func List(stateRoot string, expectedDomain domain.ID) ([]Record, error) {
	if _, err := domain.Parse(string(expectedDomain)); err != nil {
		return nil, err
	}
	root, err := openStateRoot(stateRoot)
	if err != nil {
		return nil, fmt.Errorf("project state root: %w", err)
	}
	defer root.Close()
	dir, err := openChild(root, "projects", false)
	if errors.Is(err, os.ErrNotExist) {
		return []Record{}, nil
	}
	if err != nil {
		return nil, err
	}
	defer dir.Close()
	f, err := dir.Open(".")
	if err != nil {
		return nil, err
	}
	entries, readErr := f.ReadDir(1025)
	closeErr := f.Close()
	if errors.Is(readErr, io.EOF) {
		readErr = nil
	}
	if err := errors.Join(readErr, closeErr); err != nil {
		return nil, err
	}
	if len(entries) > 1024 {
		return nil, errors.New("project registry exceeds 1024 entries")
	}
	results := make([]Record, 0, len(entries))
	for _, entry := range entries {
		name := entry.Name()
		if name == setupName {
			continue
		}
		// Atomic publications can leave private temporary files after interruption.
		if projectListTemporary(expectedDomain, name) {
			continue
		}
		if strings.HasPrefix(name, ".replacement-") {
			if err := admitReplacementListEntry(dir, expectedDomain, name); err != nil {
				return nil, err
			}
			continue
		}
		if entry.IsDir() || !strings.HasSuffix(name, ".json") {
			return nil, fmt.Errorf("unexpected project registry entry %q", name)
		}
		key := strings.TrimSuffix(name, ".json")
		if err := validateKey(expectedDomain, key); err != nil {
			return nil, fmt.Errorf("invalid project registry key %q: %w", name, err)
		}
		record, _, err := loadRecord(dir, expectedDomain, key)
		if err != nil {
			return nil, fmt.Errorf("load project %q: %w", key, err)
		}
		results = append(results, record)
	}
	sort.Slice(results, func(i, j int) bool { return results[i].Name < results[j].Name })
	return results, nil
}

// Replacement metadata is not a project key. Admit the exact known schemas,
// private file and canonical operation/name key before excluding the entry.
// Unknown hidden files still reach the normal invalid-key rejection.
func admitReplacementListEntry(dir *os.Root, d domain.ID, key string) error {
	raw, _, err := readDocument(dir, key)
	if err != nil {
		return err
	}
	if strings.HasPrefix(key, ".replacement-history-") {
		receipt, err := decodeReplacement(raw, d, "")
		if err != nil {
			return err
		}
		if key != replacementHistory(receipt) {
			return fmt.Errorf("replacement history differs from exact operation key")
		}
		return nil
	}
	name := strings.TrimSuffix(strings.TrimPrefix(key, ".replacement-"), ".json")
	if err := validateKey(d, name); err != nil {
		return err
	}
	receipt, err := decodeReplacement(raw, d, name)
	if err != nil {
		return err
	}
	if key != replacementName(receipt.Before.Name) {
		return fmt.Errorf("replacement pending receipt differs from exact project key")
	}
	current, _, err := loadRecord(dir, d, name)
	if err != nil {
		return err
	}
	if current != receipt.Before && current != receipt.Next() {
		return fmt.Errorf("pending replacement differs from current project bookmark")
	}
	return nil
}

// Skip only the atomic filenames generated by project publication. An unknown
// hidden metadata file cannot disappear merely by adding a temporary suffix.
func projectListTemporary(d domain.ID, key string) bool {
	prefix, nonce, ok := strings.Cut(key, ".json.tmp-")
	if !ok || len(nonce) != 32 {
		return false
	}
	for _, c := range nonce {
		if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f') {
			return false
		}
	}
	key = prefix + ".json"
	if key == setupName {
		return true
	}
	if strings.HasPrefix(key, ".replacement-history-") {
		return validUUID(strings.TrimSuffix(strings.TrimPrefix(key, ".replacement-history-"), ".json"))
	}
	if strings.HasPrefix(key, ".replacement-") {
		return validateKey(d, strings.TrimSuffix(strings.TrimPrefix(key, ".replacement-"), ".json")) == nil
	}
	return validateKey(d, prefix) == nil
}
